### ISSUE TITLE
Native iOS call interface doesn't appear on outgoing calls.

### ISSUE THREAD

**Issue by HerpGuy88** [hoxfon/react-native-twilio-programmable-voice#124] opened 2019-06-27 21:46 UTC
Please include the following information for better support

The more context you provide around this issue the faster the community can help you

Did you follow all the instructions as specified in the Twilio Quickstart repositories?
Yes.
What version of React Native are you running?
0.59.9
What version of react-native-twilio-programmable-voice are you running?
3.21.1.
What device are you using? (e.g iOS10 simulator, Android 7 device)?
iPhone 8 (actual device, not a simulator)
Is your app running in foreground, background or not running?
Foreground
Is there any relevant message in the log?
If using iOS, which pod version are you using?
2.0.0
Steps to reproduce:

Follow installation instructions as directed.
For ComponentWillMount on main app.
- Fetch Token from server.
- Call TwilioVoice.initWithToken.
- Call TwilioVoice.addEventListener for event 'deviceReader', and change state of 'TwilioReady:' to true.
- Call TwilioVoice.configureCallKit. 

In the body of the app:
- Create a button with 'TwilioVoice.connect' onButtonPress.

Run the app and press the button.

Almost everything works. I can make and receive calls.  However, the native iOS call interface does not appear for outgoing calls. It DOES appear for incoming calls, and is correctly configured with App name.

Advanced:
Have you tried adding break point using AndroidStudio or XCode and analyse the logs?
can share a project with issue? 
NA
Did you try to reinstall the pods completely? 
No

**Comment by alihandogrul** [comment] 2019-08-02 15:25
Any solution? @HerpGuy88

**Comment by HerpGuy88** [comment] 2019-08-09 15:24
> Any solution? @HerpGuy88

None yet. I've made a primitive mockup modal, but it's functionality is limited. 

Are you having the same issue?

**Comment by fabriziomoscon** [comment] 2020-02-15 23:41
> However, the native iOS call interface does not appear for outgoing calls
This is not the expected behaviour. An outgoing call is initiated by an action from a React-Native screen and you need to build a React screen to control the call.
I am not sure if it is possible to launch the iOS Call native screen. If you know how to do it, please let me know.

**Comment by jdegger** [comment] 2020-10-27 11:54
As mentioned by @fabriziomoscon, the requested behaviour is outside of the scope of this plugin. You have to create your own interface for this when the app is in the foreground. 

Since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.

**Closed by jdegger** 2020-10-27 11:54 UTC
