### ISSUE TITLE
The callback initWithAccessToken() exists in module RNTwilioVoice

### ISSUE THREAD

**Issue by rochapablo** [hoxfon/react-native-twilio-programmable-voice#103] opened 2018-10-17 11:31 UTC
For some reason, only after the **first build** when I open the app, I get the follow error; after that it all run normally.

```
10-17 08:26:33.303 5164-5253/ D/RNTwilioVoice: initWithAccessToken ACTION_FCM_TOKEN
    Registering with FCM
10-17 08:26:33.313 5164-5252/ E/ReactNativeJS: The callback initWithAccessToken() exists in module RNTwilioVoice, but only one callback may be registered to a function in a native module.
10-17 08:26:33.323 5164-5253/ E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: , PID: 5164
    com.facebook.react.common.JavascriptException: The callback initWithAccessToken() exists in module RNTwilioVoice, but only one callback may be registered to a function in a native module., stack:
    __invokeCallback@2034:20
    <unknown>@1844:31
    __guard@1982:11
    invokeCallbackAndReturnFlushedQueue@1843:20
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
        at java.lang.Thread.run(Thread.java:818)
```

Any idea what that could be?

**Testing on Device**

```
"react": "16.0.0-alpha.12"
"react-native": "^0.48.4"
"react-native-twilio-programmable-voice": "v3.21.0"
```

**Comment by fabriziomoscon** [comment] 2018-12-15 17:57
I can reproduce this error and I am looking for a fix.

**Comment by codingwaysarg** [comment] 2019-01-08 13:59
Hi! Any news about this issue? Thanks

**Comment by mateodaza** [comment] 2019-02-16 15:26
I solved this issue by setting android microphone permissions first

**Comment by jdegger** [comment] 2020-10-27 12:02
This issue seems to be solved right now.

Since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.

**Closed by jdegger** 2020-10-27 12:02 UTC
