### ISSUE TITLE
Twillio.connect() auto disconected

### ISSUE THREAD

**Issue by gusleo** [hoxfon/react-native-twilio-programmable-voice#116] opened 2019-02-20 05:54 UTC
Please include the following information for better support

The more context you provide around this issue the faster the community can help you

Did you follow all the instructions as specified in the Twilio Quickstart repositories?
yes
What version of React Native are you running?
0.55.2
What version of react-native-twilio-programmable-voice are you running?
3.21.1
What device are you using? (e.g iOS10 simulator, Android 7 device)?
Android Emulator API 26
Is your app running in foreground, background or not running?
foreground
Is there any relevant message in the log?
yes

Step to reproduce
After successfully get access token, i'm make call to phonenumber but after initialize success, twillio status connect with null call_from and call_to and in one second twillio status disconected.
![screenshot_185](https://user-images.githubusercontent.com/15825376/53069479-17b88780-3517-11e9-8b32-64d4e02469b9.png)

**Comment by whwright** [comment] 2019-06-05 18:37
Any updates here? It appears that I am having the same issue. (react native 0.59.8, react-native-twilio-programmable-voice 3.21.1, android emulator API 28)

**Comment by MssMaster** [comment] 2019-08-23 12:46
@whwright , Facing the same issue can you please guide me that what to do on backend to resolve this issue, I have been getting this issue from last night. Your support will be appreciated

**Comment by ilhamsa1** [comment] 2020-02-11 04:43
@whwright , i have same issue...
Have you solved it?

**Comment by Samsritha1596** [comment] 2020-08-27 14:39
I am also facing this issue. Any updatee here ?

**Comment by jdegger** [comment] 2020-10-27 12:05
I see that people are actively having problems with this. Please re-test if you also encounter problems on the newest version of this plugin.

If people still have this error, we will re-open this issue but please include a reproducible example. 

Since a long time has passed I will be closing this issue. Read our repository update in #158.

**Closed by jdegger** 2020-10-27 12:05 UTC

**Comment by Samsritha1596** [comment] 2020-10-28 04:40
Hi

The above issue was resolved...

I am having another issue, is it possible to make app to app calling using
twilio in React native..Currently i m looking for this solution. Please let
me know. Thanks

**Comment by jdegger** [comment] 2020-10-28 06:53
Hi @Samsritha1596, I refer you to the Twilio docs. https://www.twilio.com/docs/voice/client/tutorials/calls-between-devices

**Comment by Samsritha1596** [comment] 2020-10-28 11:44
Thanks

**Comment by Samsritha1596** [comment] 2020-10-28 17:32
Hi

I m not getting call_state from connectionDidConnect listener..

Thanks

**Comment by jdegger** [comment] 2020-10-28 19:40
Please file a bug report in a new issue with the issue template filled out and as much information as you have.
