### ISSUE TITLE
No call_to or call_from returns from connectionDidConnect from ios

### ISSUE THREAD

**Issue by topjun** [hoxfon/react-native-twilio-programmable-voice#62] opened 2018-01-07 08:30 UTC
Hi there,
there is No call_to or call_from returns from connectionDidConnect from ios, only {"call_state":"CONNECTED","call_sid":"CAfe03b29d8339052389e348cdb44aa2f4"} has been returned. Any thoughts?

Thanks,
Jun

**Comment by fabriziomoscon** [comment] 2018-01-08 18:20
Might be a duplicate of this: https://github.com/hoxfon/react-native-twilio-programmable-voice/issues/44
?

**Comment by topjun** [comment] 2018-01-08 21:02
There is no "to" or "from" returned neither from "data":
TwilioVoice.addEventListener('connectionDidConnect', (data) => {} 

thanks.

**Comment by fabriziomoscon** [comment] 2018-01-09 09:07
@topjun I am looking at this: https://github.com/hoxfon/react-native-twilio-programmable-voice/blob/master/ios/RNTwilioVoice/RNTwilioVoice.m#L325-L332
I debugged making a call with XCode and `call` doens't contain `to` or `from`.
<img width="761" alt="screen shot 2018-01-09 at 09 02 50" src="https://user-images.githubusercontent.com/721890/34712887-5912a2c4-f51c-11e7-8a1f-84ab926248d9.png">

If you need these parameters you need to check with the official Twilio SDK and the Twilio mobile team whether they are willing to make this change.

**Comment by jdegger** [comment] 2020-10-27 12:06
Hi, since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.

**Closed by jdegger** 2020-10-27 12:06 UTC
Labels: iOS
